/* 
 * This is an auto-generated file based on the 
 * configuration of the iDigi Connector project.
 * 
 * Do not edit this file.
 */

/* Platform definitions */
#define CONNECTOR_LITTLE_ENDIAN

/* Configuration definitions */

/* General category */
#define CONNECTOR_MAC_ADDRESS                         {0x00, 0x04, 0x9F, 0x01, 0xA0, 0x60}
#define CONNECTOR_DEVICE_TYPE                         "myDeviceType"
#define CONNECTOR_VENDOR_ID                           0x04000035 // 0x0300006F com 0x04000035 co.uk
#define FLASH_PART_0_VER                         	  0x00010000

/* Network category */
#define CONNECTOR_CONNECTION_TYPE                     connector_connection_type_lan

/* Services category */
#define CONNECTOR_DATA_SERVICE
#define CONNECTOR_MSG_MAX_TRANSACTION                 1
#define CONNECTOR_NO_COMPRESSION

/* Advanced category */
#define CONNECTOR_CLOUD_URL                           "my.idigi.co.uk"
#define CONNECTOR_TX_KEEPALIVE_IN_SECONDS             75
#define CONNECTOR_RX_KEEPALIVE_IN_SECONDS             75
#define CONNECTOR_WAIT_COUNT                          5
#define IPCFG_default_enet_device				  0

#define CONNECTOR_FILE_SYSTEM
#define FILE_SYSTEM_SDCARD
#define CONNECTOR_FILE_SYSTEM_MAX_PATH_LENGTH   256

#define CONNECTOR_FIRMWARE_SERVICE
