/* 
 * This is an auto-generated file based on the 
 * configuration of the iDigi Connector project.
 * 
 * Do not edit this file.
 */

/* Platform definitions */
#define CONNECTOR_LITTLE_ENDIAN

/* Configuration definitions */

/* General category */
//#define CONNECTOR_MAC_ADDRESS                         {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
//#define CONNECTOR_VENDOR_ID                           0x00000001
//#define CONNECTOR_CLOUD_URL                           "login.etherios.com"

#ifndef CONNECTOR_MAC_ADDRESS
#error "Please define a MAC address in connector_config.h"
#endif

#ifndef CONNECTOR_VENDOR_ID
#error "Please define the Vendor ID in connector_config.h"
#endif

#ifndef CONNECTOR_VENDOR_ID
#error "Please define the Device Cloud URL connector_config.h"
#endif



#define CONNECTOR_DEVICE_TYPE                         "TWRK60N512"
/* Network category */
#define CONNECTOR_CONNECTION_TYPE                     connector_connection_type_lan
//#define CONNECTOR_TRANSPORT_TCP

/* Services category */
//#define CONNECTOR_DATA_POINTS
//#define CONNECTOR_MSG_MAX_TRANSACTION                 1
//#define CONNECTOR_NO_COMPRESSION

/* Advanced category */
#define CONNECTOR_TX_KEEPALIVE_IN_SECONDS             75
#define CONNECTOR_RX_KEEPALIVE_IN_SECONDS             75
#define CONNECTOR_WAIT_COUNT                          5

//#define CONNECTOR_FILE_SYSTEM
//#define FILE_SYSTEM_USB
//#define CONNECTOR_FILE_SYSTEM_MAX_PATH_LENGTH   256

//#define CONNECTOR_FIRMWARE_SERVICE
#define CONNECTOR_RCI_SERVICE
#define CONNECTOR_RCI_MAXIMUM_CONTENT_LENGTH 	256
