/* 
 * This is an auto-generated file based on the 
 * configuration of the iDigi Connector project.
 * 
 * Do not edit this file.
 */

/* Platform definitions */
#define CONNECTOR_LITTLE_ENDIAN

/* Configuration definitions */

/* General category */
#define CONNECTOR_DEVICE_TYPE                         "TWRK60N512"

/* Network category */
#define CONNECTOR_CONNECTION_TYPE                     connector_connection_type_lan

/* Services category */
#define CONNECTOR_DATA_SERVICE
#define CONNECTOR_MSG_MAX_TRANSACTION                 1
#define CONNECTOR_NO_COMPRESSION

/* Advanced category */
#define CONNECTOR_TX_KEEPALIVE_IN_SECONDS             75
#define CONNECTOR_RX_KEEPALIVE_IN_SECONDS             75
#define CONNECTOR_WAIT_COUNT                          5

#define CONNECTOR_FILE_SYSTEM
#define FILE_SYSTEM_SDCARD
#define CONNECTOR_FILE_SYSTEM_MAX_PATH_LENGTH   256

#define CONNECTOR_FIRMWARE_SERVICE
#define	DEVICE_HAS_FLASH_PART_0
#define FLASH_PART_0_LEN                          0xFFFFFFFF
#define FLASH_PART_0_TYPE                         ".*\\.S19"
#define FLASH_PART_0_DESC                         "srec Image"
#define FLASH_PART_0_VER                          {0,0,0,1}

#define CONNECTOR_RCI_SERVICE
#define CONNECTOR_RCI_MAXIMUM_CONTENT_LENGTH 	256
#define CONNECTOR_CUSTOMIZE_GET_MAC_METHOD
