/* 
 * This is an auto-generated file based on the 
 * configuration of the iDigi Connector project.
 * 
 * Do not edit this file.
 */

/* Platform definitions */
#define IDIGI_LITTLE_ENDIAN

/* Configuration definitions */

/* General category */
#define IDIGI_MAC_ADDRESS                         {0x00, 0x04, 0x9F, 0x01, 0xA0, 0x60}
#define IDIGI_DEVICE_TYPE                         "myDeviceType"
#define IDIGI_VENDOR_ID                           0x0300006F // 0x0300006F com 0x04000035 co.uk
#define FLASH_PART_0_VER                          0x00010000

/* Network category */
#define IDIGI_CONNECTION_TYPE                     idigi_lan_connection_type

/* Services category */
#define IDIGI_DATA_SERVICE
#define IDIGI_MSG_MAX_TRANSACTION                 1
#define IDIGI_NO_COMPRESSION

/* Advanced category */
#define IDIGI_CLOUD_URL                           "my.idigi.com"
#define IDIGI_TX_KEEPALIVE_IN_SECONDS             75
#define IDIGI_RX_KEEPALIVE_IN_SECONDS             75
#define IDIGI_WAIT_COUNT                          5
#define IPCFG_default_enet_device				  0
